### ISSUE TITLE
Allow opening neovim :terminal in normal mode

### ISSUE THREAD

**Issue by DanielPower** [vim-test/vim-test#577] opened 2021-07-29 16:38 UTC
The current behaviour is running tests with the `neovim` strategy opens a terminal in insert mode. This makes it easy to close the terminal by pressing a key, but it means you need to switch to normal mode `<C-\><C-n>` to navigate.

I would prefer to be able to have the terminal open in normal mode, so that I can navigate the test's output, and use my other defined normal mode commands (such as split navigation) more easily. Is this something that is currently possible, or could it be introduced as an option?

**Comment by jdsutherland** [comment] 2021-08-03 02:34
Looks like dupe of https://github.com/vim-test/vim-test/issues/448

**Comment by DanielPower** [comment] 2021-08-03 14:47
That issue is similar but not quite the same as my issue. Thank you for bringing it up though, since it helped me find the location in the code where this occurs.

https://github.com/vim-test/vim-test/blob/849d378a499ada59d3326c166d44f0a118e4bdbf/autoload/test/strategy.vim#L79

In the neovim strategy, it calls `startinsert` after opening the terminal. If that's something that should be configurable in `vim-test`, then this issue can track implementing that, and I'd be happy to submit a PR. If the maintainers feel that's not something that should be configurable, I can just create my own custom strategy, and I'm okay to close this issue.

**Closed** 2021-09-15 17:43 UTC
